version: '3.8'

services:
  auth_service:
    image: authentiq
    container_name: authentiq-app
    build:
      context: ./auth
    ports:
      - "${AUTH_PORT}:${AUTH_PORT}"
    secrets:
      - mongodb_root_username
      - mongodb_root_password
    environment:
      - AUTHENTIQ_DB_USERNAME_FILE=/run/secrets/mongodb_root_username
      - AUTHENTIQ_DB_PASSWORD_FILE=/run/secrets/mongodb_root_password
    depends_on:
      - mongodb
    restart: always

  mongodb:
    image: mongo:latest
    container_name: authentiq-db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME_FILE=/run/secrets/mongodb_root_username
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/run/secrets/mongodb_root_password
    volumes:
      - type: bind
        source: ./data
        target: /data/db
    secrets:
      - mongodb_root_username
      - mongodb_root_password
    ports:
      - "27017:27017"

      
secrets:
  mongodb_root_username:
    file: mongodb_root_username.txt
  mongodb_root_password:
    file: mongodb_root_password.txt


